name: Deploy test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/my-amazing-app/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
